# Generated by Django 4.0.3 on 2024-06-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='name',
            new_name='logo_name',
        ),
        migrations.AddField(
            model_name='info',
            name='title_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
