# Generated by Django 4.0.3 on 2024-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_info_logo_name_info_title_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Site info', 'verbose_name_plural': 'Site info'},
        ),
        migrations.AddField(
            model_name='info',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='info',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='info',
            name='tiktok_link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
