# Generated by Django 4.0.3 on 2024-06-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dailytasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_clients', models.CharField(blank=True, max_length=100)),
                ('translations', models.CharField(blank=True, max_length=100)),
                ('support', models.CharField(blank=True, max_length=100)),
                ('team', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Statistics',
                'verbose_name_plural': 'Statistics',
            },
        ),
        migrations.AlterModelOptions(
            name='dailytasks',
            options={'verbose_name': 'Daily Tasks', 'verbose_name_plural': 'Daily Tasks'},
        ),
    ]
