# Generated by Django 4.0.3 on 2024-06-22 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_service_image_alter_service_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyTasks',
        ),
    ]
