# Generated by Django 4.0.3 on 2024-06-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_slider_remove_aboutus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
