# Generated by Django 4.0.3 on 2024-06-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_itservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itservice',
            options={'verbose_name': 'IT service', 'verbose_name_plural': 'IT services'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='text_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_russian',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='name_russian',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_russian',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='info',
            name='address_1_russian',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='info',
            name='address_2_russian',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='info',
            name='title_name_russian',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='itservice',
            name='full_description_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itservice',
            name='short_description_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itservice',
            name='title_russian',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='description_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_russian',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_russian',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_russian',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
