# Generated by Django 4.0.3 on 2024-06-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_itservice_options_aboutus_text_russian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_russian',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
