# Generated by Django 4.0.3 on 2024-07-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_service_image_russian'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='full_description_russian',
            field=models.TextField(blank=True),
        ),
    ]
