# Generated by Django 4.0.3 on 2024-07-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='uid',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
