# Generated by Django 4.0.3 on 2024-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_orderproduct_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='total_price',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
