# Generated by Django 4.0.3 on 2024-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_orderproduct_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
