# Generated by Django 4.0.3 on 2024-07-05 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_orderproduct_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
