# Generated by Django 4.0.3 on 2024-07-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_orderproduct_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='products',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='products',
            field=models.TextField(blank=True),
        ),
    ]
