# Generated by Django 4.0.3 on 2024-07-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_orderproduct_products_orderproduct_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('-id',), 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('-date_added',)},
        ),
    ]
