# Generated by Django 4.0.3 on 2024-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_faq_options_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('product', 'session_key')},
        ),
    ]
